spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/reactivegym
    username: developer
    password: Developer@1234


  flyway:
    url: jdbc:mysql://localhost:3306/reactivegym
    user: developer
    password: Developer@1234
